/** Public surface of the undo-redo feature (ADR-0048). Dark until M3 wires the toolbar + keybindings. */
export {
  activityDefinitionInput,
  dependencyLinkOf,
  durationResizeCommand,
  lagDragCommand,
  visualResizeCommand,
  relaneCommand,
  updateCommand,
  createActivityCommand,
  createLoeSpanCommand,
  deleteActivityCommand,
  dissolveCommand,
  dependencyAddCommand,
  dependencyEditChanged,
  dependencyEditCommand,
  dependencyRemoveCommand,
  visualStartCommand,
  autoArrangeCommand,
  bulkPlacementCommand,
  bulkDeleteCommand,
  linkChainCommand,
  pasteActivitiesCommand,
  typeChangeCommand,
  type Command,
  type CommandCoalescing,
  type RepositionLaneFn,
  type PatchActivityFieldsFn,
  type CreatePlacedActivityFn,
  type DeleteActivityFn,
  type CreateDependencyFn,
  type DeleteDependencyFn,
  type DependencyLinkInput,
  type SetVisualStartFn,
  type UpdateDependencyFn,
  type VisualPlacement,
  type BatchPositionsFn,
  type LanePlacement,
  type BatchPlacementsFn,
  type ActivityPlacement,
  type BulkDeleteActivitiesFn,
  type RestoreDeleteBatchFn,
} from './commands';
export {
  assignmentAddCommand,
  assignmentChanged,
  assignmentEditCommand,
  assignmentRemoveCommand,
  crossPlanLinkAddCommand,
  crossPlanLinkRemoveCommand,
  reparentCommand,
  reparentedRows,
  reparentLabel,
  stepsChanged,
  stepsReplaceCommand,
  type AssignmentWrites,
  type CreateAssignmentFn,
  type CreateCrossPlanLinkFn,
  type DeleteAssignmentFn,
  type DeleteCrossPlanLinkFn,
  type DisplacedDriver,
  type ReplaceStepsFn,
  type UpdateAssignmentFn,
  type UpdateParentsFn,
} from './record-commands';
export {
  usePlanEditHistory,
  MAX_HISTORY_DEPTH,
  COALESCE_WINDOW_MS,
  type PlanEditHistory,
  type StepOutcome,
} from './use-plan-edit-history';
export { usePlanUndoRedo, type PlanUndoRedo } from './use-plan-undo-redo';
export {
  historyResultMessage,
  isHistoryFailure,
  UNDO_FAILED_MESSAGE,
  REDO_FAILED_MESSAGE,
  type HistoryOutcome,
  type HistoryResult,
  type PostedHistoryResult,
  type SetAside,
} from './history-result';
export type { NotApplicableReason, ReplayContext, ReplayResult } from './replay';
export { useHistoryResult, type HistoryResultState } from './use-history-result';
export { useUndoRedoKeybindings } from './use-undo-redo-keybindings';
export { blockedHistoryResult, historyResultAction } from './history-result-host';
